languageCode = "en-us"
title = "Мой блог."
baseURL = "http://korolr.me/blog/"
publishDir = "blog"
# Site settings
theme = "hugo-cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "vuejsblog"

[params]
	name = "Alexsey Lebdev"
	description = "Describe your website"
	bio = "Боль, python и javascript"
	# Enter optionally your twitter account
	twitter = "korolr22"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "https://www.linkedin.com/in/alexsey-lebedev-8487a8130"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Энтузиаст."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/korolr22"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/korolr"
    dribble  = "https://www.dribbble.com/"
